const mongoose = require('mongoose');

const CallSchema = new mongoose.Schema(
  {
    callId: {
      type: String,
      required: true,
      unique: true,
    },

    timestamp: {
      type: Date,
      required: true,
    },

    campaignId: {
      type: String,
      required: true,
    },

    campaignName: {
      type: String,
      required: true,
    },

    payout: {
      type: Number,
      default: 0,
    },

    duration: {
      type: Number,
      default: 0,
    },

    hasRecording: {
      type: Boolean,
      default: false,
    },

    recordingUrl: {
      type: String,
      default: null,
    },

    // Generated by OpenAI Whisper
    transcript: {
      type: String,
      default: null,
    },

    // Generated by GPT
    summary: {
      type: String,
      default: null,
    },

    sentiment: {
      type: String,
      enum: ['Positive', 'Neutral', 'Negative', null],
      default: null,
    },

    // Save the full Ringba JSON response 
    rawJson: {
      type: Object,
      required: true,
    },
  },
  {
    timestamps: true, // Adds createdAt & updatedAt
  }
);

module.exports = mongoose.model('Call', CallSchema);
